# Generated by Django 4.2.13 on 2024-05-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcomments',
            name='author',
        ),
        migrations.RemoveField(
            model_name='roomcomments',
            name='room',
        ),
        migrations.DeleteModel(
            name='RoomCommentLikes',
        ),
        migrations.DeleteModel(
            name='RoomComments',
        ),
    ]
